# サイト設定
title: "My Dev Docs"
description: "Docker, Linux, Git, LaTeX, ROS2, YARP"
theme: "just-the-docs"
url: "http://iharuruki.github.io/tutorial/"

aux_links:
  "日本語":
    - "http://iharuruki.github.io/tutorial/"
  "English":
    - "http://iharuruki.github.io/tutorial/en/"

plugins:
  - jekyll-default-layout
  - jekyll-polyglot # Multi-languages plugin
  - jekyll-relative-links # 相対リンク

# 多言語設定
languages: ["ja", "en"]
default_lang: "ja"
exclude_from_localization: ["/assets", "/css", "/images"]
parallel_localization: false

just_the_docs:
  search_enabled: true
  heading_anchors: true

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Version of mermaid library
# Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
mermaid:
  vertion: "11.12.0"

# デフォルトレイアウト設定
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      has_children: false
      nav_order: 1