title: Tutorial
description: Tutorial for those planning to join a research lab
theme: just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"


url: https://iharuruki.github.io/tutorial/

# aux_links:
#   Template Repository: https://iharuruki.github.io/tutorial/

# Version of mermaid library
# Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
mermaid:
  vertion: "9.1.3"

plugins:
  - jekyll-default-layout

plugins:
  - jekyll-relative-links # 相対リンク