title: Tutorial
description: Tutorial for those planning to join a research lab
theme: just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"


url: https://iharuruki.github.io/tutorial/

aux_links:
  "日本語": "/"
  "English Site": "/en"   # 英語版のトップページURL
aux_links_new_tab: false  # Makes Aux links open in a new tab. Default is false

# Version of mermaid library
# Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
mermaid:
  vertion: "11.12.0"

plugins:
  - jekyll-default-layout
  - jekyll-polyglot
  - jekyll-relative-links # 相対リンク

# 多言語設定
languages: ["ja", "en", "th"]
default_lang: "ja"
exclude_from_localization: ["assets"] # 翻訳不要なアセットフォルダ
parallel_localization: true

sass:
  sourcemap: never

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Enable or disable the site search
search_enabled: true