title: Tutorial
description: Tutorial for those planning to join a research lab
theme: just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"


url: https://github.com/iHaruruki/tutorial.git

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Version of mermaid library
# Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
mermaid:
  vertion: "11.12.0"
